---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: lab-hgrubbs
spec:
  selector:
    app: api
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: database
  namespace: lab-hgrubbs
spec:
  selector:
    app: database
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  type: NodePort
